name:  Pipeline CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Parar containers antigos
        run: docker-compose down

      - name: Iniciar API Flask
        run: docker-compose up --build -d

      - name: Verificar se a API está rodando
        run: |
          curl --retry 10 --retry-delay 10 --retry-connrefused http://localhost:5000/score/33333333333

      - name: Instalar dependências Python (Behave e Pytest)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar testes BDD (Behave)
        run: python -m behave features/

      - name: Executar testes unitários (Pytest)
        run: python -m pytest tests/