name:  Pipeline de Integração Contínua (CI)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Parar containers antigos
        run: docker-compose down


      - name: Executar testes BDD (Behave)
        run: python -m behave features/

      - name: Executar testes unitários (Pytest)
        run: python -m pytest tests/
        
      - name: Construir e rodar a API Flask
        run: docker-compose up --build -d